django-form-master/accounts/urls.py
from django.urls import path
from . import views

#  accounts:index
app_name = 'accounts'

# accounts/
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

django-form-master/boards/urls.py
from django.urls import path
from . import views

# 경로 앱 이름 지정 'boards:detail'
app_name = 'boards'

# boards/
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_pk>/', views.detail, name='detail'),  # boards/3/
    path('create/', views.create, name='create'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/update/', views.update, name='update'),
]

django-form-master/django_form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

django-form-master/accounts/models.py
from django.db import models

# Create your models here.

django-form-master/boards/models.py
from django.db import models


class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django-form-master/boards/forms.py
from django import forms
from .models import Board


class BoardForm(forms.ModelForm):
    #  Model 의 대한 정보들 입력
    class Meta:
        model = Board
        fields = ('title', 'content', )

django-form-master/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('boards:index')
    else:  # GET accounts/signup/
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        #  사용자 입력 유효성 검사
        if form.is_valid():
            #  로그인
            auth_login(request, form.get_user())
            return redirect('boards:index')
    else:  # GET /accounts/login/ -> html 페이지만 렌더링
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def logout(request):
    #  로그아웃 로직
    auth_logout(request)
    return redirect('boards:index')

django-form-master/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_GET, require_http_methods
from .models import Board
from .forms import BoardForm


# Board 의 리스트
@require_GET
def index(request):
    boards = Board.objects.order_by('-pk')
    context = {'boards': boards}
    return render(request, 'boards/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm()
    context = {'form': form}
    return render(request, 'boards/form.html', context)


# boards/3/
@require_GET
def detail(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    context = {'board': board}
    return render(request, 'boards/detail.html', context)


# POST boards/3/delete/
@require_POST
def delete(request, board_pk):
    # 특정 보드를 불러와서 삭제한다.
    board = get_object_or_404(Board, pk=board_pk)
    board.delete()
    return redirect('boards:index')


@require_http_methods(['GET', 'POST'])
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    #  POST boards/3/update/
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save()
            return redirect('boards:detail', board.pk)
    #  GET boards/3/update/
    else:
        form = BoardForm(instance=board)  # board 데이터 할당
    context = {
        'form': form,
        'board_pk': board_pk,
    }
    return render(request, 'boards/form.html', context)

django-form-master/accounts/templates/accounts/login.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>로그인</h1>
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="로그인" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}

django-form-master/accounts/templates/accounts/signup.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>회원가입</h1>
<!-- POST accounts/signup/ -->
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit="회원가입" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}

django-form-master/boards/templates/boards/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% bootstrap_css %}
    <title>Board</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>

django-form-master/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1>Detail</h1>
    <hr />
    <p>글 번호: {{ board.pk }}</p>
    <p>글 제목: {{ board.title }}</p>
    <p>글 내용: {{ board.content }}</p>
    <p>글 생성시각: {{ board.created_at }}</p>
    <p>글 수정시각: {{ board.updated_at }}</p>
    <hr />
    <form action="{% url 'boards:delete' board.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제하기" />
    </form>
    <a href="{% url 'boards:update' board.pk %}">[수정하기]</a>
    <a href="{% url 'boards:index' %}">[뒤로가기]</a>
{% endblock %}

django-form-master/boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
    <h1>새로운 게시글 작성</h1>
    {% else %} <!-- Update 가 들어오면 -->
    <h1>게시글 수정</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit="Submit" reset="Cancel" %}
        {% endbuttons %}
    </form>
    {% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}">[뒤로가기]</a>
    {% else %}
    <a href="{% url 'boards:detail' board_pk %}">[뒤로가기]</a>
    {% endif %}
{% endblock %}

django-form-master/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
<ul class="nav justify-content-end">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
  </li>
</ul>

<div class="jumbotron">
    <h1>게시글 목록</h1>
    {% if user.is_authenticated %}
        <h3>{{ user.username }}님 안녕하세요!</h3>
    {% endif %}
    <a href="{% url 'boards:create' %}">[게시글 작성]</a>
</div>

{% for board in boards %}
    <div class="card">
        <div class="card-body">
            <p>{{ board.pk }}. {{board.title}}</p>
            <a class="btn btn-info" href="{% url 'boards:detail' board.pk %}">상세보기</a>
        </div>
    </div>
    <br />
{% empty %}
    <p><strong>아직 작성된 글이 없습니다.</strong></p>
{% endfor %}

{% endblock %}